import { pgTable, text, timestamp, varchar, integer, boolean, jsonb } from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: varchar("id", { length: 128 }).primaryKey(),
  role: varchar("role", { length: 32 }).notNull().default("citizen"),
  email: varchar("email", { length: 255 }),
  phone: varchar("phone", { length: 32 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const citizens = pgTable("citizens", {
  id: varchar("id", { length: 64 }).primaryKey(),
  userId: varchar("user_id", { length: 128 }).references(() => users.id, { onDelete: "cascade" }),
  name: varchar("name", { length: 255 }).notNull(),
  email: varchar("email", { length: 255 }),
  phone: varchar("phone", { length: 32 }),
  city: varchar("city", { length: 128 }),
  currentLocation: text("current_location"),
  address: text("address"),
  state: varchar("state", { length: 128 }),
  pincode: varchar("pincode", { length: 16 }),
  emergencyContact: varchar("emergency_contact", { length: 32 }),
  status: varchar("status", { length: 32 }).default("Active").notNull(),
  joinedAt: varchar("joined_at", { length: 32 }).notNull(),
  lastLoginAt: varchar("last_login_at", { length: 64 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const lawyers = pgTable("lawyers", {
  id: varchar("id", { length: 64 }).primaryKey(),
  userId: varchar("user_id", { length: 128 }).references(() => users.id, { onDelete: "cascade" }),
  name: varchar("name", { length: 255 }).notNull(),
  email: varchar("email", { length: 255 }).notNull(),
  phone: varchar("phone", { length: 32 }).notNull(),
  category: varchar("category", { length: 64 }).notNull(),
  roleTitle: varchar("role_title", { length: 128 }),
  city: varchar("city", { length: 128 }).notNull(),
  cities: jsonb("cities").$type<string[]>().default([]),
  currentLocation: text("current_location"),
  area: varchar("area", { length: 128 }),

  barId: varchar("bar_id", { length: 128 }).notNull(),
  experienceYears: integer("experience_years").default(0).notNull(),
  rating: text("rating").default("4.5").notNull(),
  status: varchar("status", { length: 32 }).default("Pending").notNull(),
  activeCases: integer("active_cases").default(0).notNull(),
  photoUrl: text("photo_url"),
  idProofUrl: text("id_proof_url"),
  idProofFileName: varchar("id_proof_file_name", { length: 255 }),
  officeAddress: text("office_address"),
  bio: text("bio"),
  languages: jsonb("languages").$type<string[]>().default([]),
  practiceAreas: jsonb("practice_areas").$type<any[]>().default([]),
  specializations: jsonb("specializations").$type<string[]>().default([]),
  legalServices: jsonb("legal_services").$type<string[]>().default([]),
  courts: jsonb("courts").$type<string[]>().default([]),
  awards: jsonb("awards").$type<any[]>().default([]),
  ratingCount: integer("rating_count").default(0),
  consultationFee: integer("consultation_fee").default(1000),
  availabilityStatus: varchar("availability_status", { length: 32 }).default("Online"),
  bankName: varchar("bank_name", { length: 128 }),
  accountNumber: varchar("account_number", { length: 64 }),
  ifscCode: varchar("ifsc_code", { length: 32 }),
  joinedAt: varchar("joined_at", { length: 32 }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const adminProfiles = pgTable("admin_profiles", {
  id: varchar("id", { length: 64 }).primaryKey(),
  userId: varchar("user_id", { length: 128 }).references(() => users.id, { onDelete: "cascade" }),
  name: varchar("name", { length: 255 }).notNull(),
  email: varchar("email", { length: 255 }).notNull(),
  phone: varchar("phone", { length: 32 }),
  role: varchar("role", { length: 64 }).default("superadmin").notNull(),
  avatarUrl: text("avatar_url"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});
