/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as CitizenLoginRouteImport } from './routes/citizen-login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LawyerRouteImport } from './routes/lawyer'
import { Route as LawyerRegisterRouteImport } from './routes/lawyer-register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCasesRouteImport } from './routes/admin.cases'
import { Route as AdminDataManagementRouteImport } from './routes/admin.data-management'
import { Route as AdminKnowledgeBaseRouteImport } from './routes/admin.knowledge-base'
import { Route as AdminLawyersRouteImport } from './routes/admin.lawyers'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenCreateCaseRouteImport } from './routes/citizen.create-case'
import { Route as CitizenMyCasesRouteImport } from './routes/citizen.my-cases'
import { Route as CitizenNotificationsRouteImport } from './routes/citizen.notifications'
import { Route as CitizenProfileRouteImport } from './routes/citizen.profile'
import { Route as CitizenSubscriptionsRouteImport } from './routes/citizen.subscriptions'
import { Route as LawyerIndexRouteImport } from './routes/lawyer.index'
import { Route as LawyerAiAssistantRouteImport } from './routes/lawyer.ai-assistant'
import { Route as LawyerCasesRouteImport } from './routes/lawyer.cases'
import { Route as LawyerKnowledgeBaseRouteImport } from './routes/lawyer.knowledge-base'
import { Route as LawyerNotificationsRouteImport } from './routes/lawyer.notifications'
import { Route as LawyerProfileRouteImport } from './routes/lawyer.profile'
import { Route as LawyerQaAssistantRouteImport } from './routes/lawyer.qa-assistant'
import { Route as LawyerRevenueRouteImport } from './routes/lawyer.revenue'
import { Route as LawyerSummarizerRouteImport } from './routes/lawyer.summarizer'
import { Route as CitizenCasesIdRouteImport } from './routes/citizen.cases.$id'
import { Route as CitizenChatIdRouteImport } from './routes/citizen.chat.$id'
import { Route as LawyerCasesIndexRouteImport } from './routes/lawyer.cases.index'
import { Route as LawyerCasesIdRouteImport } from './routes/lawyer.cases.$id'
import { Route as LawyerChatIdRouteImport } from './routes/lawyer.chat.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenLoginRoute = CitizenLoginRouteImport.update({
  id: '/citizen-login',
  path: '/citizen-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerRoute = LawyerRouteImport.update({
  id: '/lawyer',
  path: '/lawyer',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerRegisterRoute = LawyerRegisterRouteImport.update({
  id: '/lawyer-register',
  path: '/lawyer-register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataManagementRoute = AdminDataManagementRouteImport.update({
  id: '/data-management',
  path: '/data-management',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeBaseRoute = AdminKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLawyersRoute = AdminLawyersRouteImport.update({
  id: '/lawyers',
  path: '/lawyers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenCreateCaseRoute = CitizenCreateCaseRouteImport.update({
  id: '/create-case',
  path: '/create-case',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenMyCasesRoute = CitizenMyCasesRouteImport.update({
  id: '/my-cases',
  path: '/my-cases',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenNotificationsRoute = CitizenNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenProfileRoute = CitizenProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenSubscriptionsRoute = CitizenSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => CitizenRoute,
} as any)
const LawyerIndexRoute = LawyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerAiAssistantRoute = LawyerAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerCasesRoute = LawyerCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerKnowledgeBaseRoute = LawyerKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerNotificationsRoute = LawyerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerProfileRoute = LawyerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerQaAssistantRoute = LawyerQaAssistantRouteImport.update({
  id: '/qa-assistant',
  path: '/qa-assistant',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerRevenueRoute = LawyerRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => LawyerRoute,
} as any)
const LawyerSummarizerRoute = LawyerSummarizerRouteImport.update({
  id: '/summarizer',
  path: '/summarizer',
  getParentRoute: () => LawyerRoute,
} as any)
const CitizenCasesIdRoute = CitizenCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenChatIdRoute = CitizenChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => CitizenRoute,
} as any)
const LawyerCasesIndexRoute = LawyerCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LawyerCasesRoute,
} as any)
const LawyerCasesIdRoute = LawyerCasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LawyerCasesRoute,
} as any)
const LawyerChatIdRoute = LawyerChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => LawyerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-docs': typeof ApiDocsRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/citizen-login': typeof CitizenLoginRoute
  '/contact': typeof ContactRoute
  '/lawyer': typeof LawyerRouteWithChildren
  '/lawyer-register': typeof LawyerRegisterRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/data-management': typeof AdminDataManagementRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/create-case': typeof CitizenCreateCaseRoute
  '/citizen/my-cases': typeof CitizenMyCasesRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/subscriptions': typeof CitizenSubscriptionsRoute
  '/lawyer/ai-assistant': typeof LawyerAiAssistantRoute
  '/lawyer/cases': typeof LawyerCasesRouteWithChildren
  '/lawyer/knowledge-base': typeof LawyerKnowledgeBaseRoute
  '/lawyer/notifications': typeof LawyerNotificationsRoute
  '/lawyer/profile': typeof LawyerProfileRoute
  '/lawyer/qa-assistant': typeof LawyerQaAssistantRoute
  '/lawyer/revenue': typeof LawyerRevenueRoute
  '/lawyer/summarizer': typeof LawyerSummarizerRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/lawyer/': typeof LawyerIndexRoute
  '/citizen/cases/$id': typeof CitizenCasesIdRoute
  '/citizen/chat/$id': typeof CitizenChatIdRoute
  '/lawyer/cases/$id': typeof LawyerCasesIdRoute
  '/lawyer/chat/$id': typeof LawyerChatIdRoute
  '/lawyer/cases/': typeof LawyerCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/citizen-login': typeof CitizenLoginRoute
  '/contact': typeof ContactRoute
  '/lawyer-register': typeof LawyerRegisterRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/data-management': typeof AdminDataManagementRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/create-case': typeof CitizenCreateCaseRoute
  '/citizen/my-cases': typeof CitizenMyCasesRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/subscriptions': typeof CitizenSubscriptionsRoute
  '/lawyer/ai-assistant': typeof LawyerAiAssistantRoute
  '/lawyer/knowledge-base': typeof LawyerKnowledgeBaseRoute
  '/lawyer/notifications': typeof LawyerNotificationsRoute
  '/lawyer/profile': typeof LawyerProfileRoute
  '/lawyer/qa-assistant': typeof LawyerQaAssistantRoute
  '/lawyer/revenue': typeof LawyerRevenueRoute
  '/lawyer/summarizer': typeof LawyerSummarizerRoute
  '/admin': typeof AdminIndexRoute
  '/citizen': typeof CitizenIndexRoute
  '/lawyer': typeof LawyerIndexRoute
  '/citizen/cases/$id': typeof CitizenCasesIdRoute
  '/citizen/chat/$id': typeof CitizenChatIdRoute
  '/lawyer/cases/$id': typeof LawyerCasesIdRoute
  '/lawyer/chat/$id': typeof LawyerChatIdRoute
  '/lawyer/cases': typeof LawyerCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-docs': typeof ApiDocsRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/citizen-login': typeof CitizenLoginRoute
  '/contact': typeof ContactRoute
  '/lawyer': typeof LawyerRouteWithChildren
  '/lawyer-register': typeof LawyerRegisterRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/data-management': typeof AdminDataManagementRoute
  '/admin/knowledge-base': typeof AdminKnowledgeBaseRoute
  '/admin/lawyers': typeof AdminLawyersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/create-case': typeof CitizenCreateCaseRoute
  '/citizen/my-cases': typeof CitizenMyCasesRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/subscriptions': typeof CitizenSubscriptionsRoute
  '/lawyer/ai-assistant': typeof LawyerAiAssistantRoute
  '/lawyer/cases': typeof LawyerCasesRouteWithChildren
  '/lawyer/knowledge-base': typeof LawyerKnowledgeBaseRoute
  '/lawyer/notifications': typeof LawyerNotificationsRoute
  '/lawyer/profile': typeof LawyerProfileRoute
  '/lawyer/qa-assistant': typeof LawyerQaAssistantRoute
  '/lawyer/revenue': typeof LawyerRevenueRoute
  '/lawyer/summarizer': typeof LawyerSummarizerRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/lawyer/': typeof LawyerIndexRoute
  '/citizen/cases/$id': typeof CitizenCasesIdRoute
  '/citizen/chat/$id': typeof CitizenChatIdRoute
  '/lawyer/cases/$id': typeof LawyerCasesIdRoute
  '/lawyer/chat/$id': typeof LawyerChatIdRoute
  '/lawyer/cases/': typeof LawyerCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/api-docs'
    | '/citizen'
    | '/citizen-login'
    | '/contact'
    | '/lawyer'
    | '/lawyer-register'
    | '/login'
    | '/register'
    | '/admin/cases'
    | '/admin/data-management'
    | '/admin/knowledge-base'
    | '/admin/lawyers'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/revenue'
    | '/admin/users'
    | '/citizen/create-case'
    | '/citizen/my-cases'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/citizen/subscriptions'
    | '/lawyer/ai-assistant'
    | '/lawyer/cases'
    | '/lawyer/knowledge-base'
    | '/lawyer/notifications'
    | '/lawyer/profile'
    | '/lawyer/qa-assistant'
    | '/lawyer/revenue'
    | '/lawyer/summarizer'
    | '/admin/'
    | '/citizen/'
    | '/lawyer/'
    | '/citizen/cases/$id'
    | '/citizen/chat/$id'
    | '/lawyer/cases/$id'
    | '/lawyer/chat/$id'
    | '/lawyer/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-docs'
    | '/citizen-login'
    | '/contact'
    | '/lawyer-register'
    | '/login'
    | '/register'
    | '/admin/cases'
    | '/admin/data-management'
    | '/admin/knowledge-base'
    | '/admin/lawyers'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/revenue'
    | '/admin/users'
    | '/citizen/create-case'
    | '/citizen/my-cases'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/citizen/subscriptions'
    | '/lawyer/ai-assistant'
    | '/lawyer/knowledge-base'
    | '/lawyer/notifications'
    | '/lawyer/profile'
    | '/lawyer/qa-assistant'
    | '/lawyer/revenue'
    | '/lawyer/summarizer'
    | '/admin'
    | '/citizen'
    | '/lawyer'
    | '/citizen/cases/$id'
    | '/citizen/chat/$id'
    | '/lawyer/cases/$id'
    | '/lawyer/chat/$id'
    | '/lawyer/cases'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/api-docs'
    | '/citizen'
    | '/citizen-login'
    | '/contact'
    | '/lawyer'
    | '/lawyer-register'
    | '/login'
    | '/register'
    | '/admin/cases'
    | '/admin/data-management'
    | '/admin/knowledge-base'
    | '/admin/lawyers'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/revenue'
    | '/admin/users'
    | '/citizen/create-case'
    | '/citizen/my-cases'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/citizen/subscriptions'
    | '/lawyer/ai-assistant'
    | '/lawyer/cases'
    | '/lawyer/knowledge-base'
    | '/lawyer/notifications'
    | '/lawyer/profile'
    | '/lawyer/qa-assistant'
    | '/lawyer/revenue'
    | '/lawyer/summarizer'
    | '/admin/'
    | '/citizen/'
    | '/lawyer/'
    | '/citizen/cases/$id'
    | '/citizen/chat/$id'
    | '/lawyer/cases/$id'
    | '/lawyer/chat/$id'
    | '/lawyer/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiDocsRoute: typeof ApiDocsRoute
  CitizenRoute: typeof CitizenRouteWithChildren
  CitizenLoginRoute: typeof CitizenLoginRoute
  ContactRoute: typeof ContactRoute
  LawyerRoute: typeof LawyerRouteWithChildren
  LawyerRegisterRoute: typeof LawyerRegisterRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen-login': {
      id: '/citizen-login'
      path: '/citizen-login'
      fullPath: '/citizen-login'
      preLoaderRoute: typeof CitizenLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer': {
      id: '/lawyer'
      path: '/lawyer'
      fullPath: '/lawyer'
      preLoaderRoute: typeof LawyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-register': {
      id: '/lawyer-register'
      path: '/lawyer-register'
      fullPath: '/lawyer-register'
      preLoaderRoute: typeof LawyerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-management': {
      id: '/admin/data-management'
      path: '/data-management'
      fullPath: '/admin/data-management'
      preLoaderRoute: typeof AdminDataManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge-base': {
      id: '/admin/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/admin/knowledge-base'
      preLoaderRoute: typeof AdminKnowledgeBaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lawyers': {
      id: '/admin/lawyers'
      path: '/lawyers'
      fullPath: '/admin/lawyers'
      preLoaderRoute: typeof AdminLawyersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/create-case': {
      id: '/citizen/create-case'
      path: '/create-case'
      fullPath: '/citizen/create-case'
      preLoaderRoute: typeof CitizenCreateCaseRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/my-cases': {
      id: '/citizen/my-cases'
      path: '/my-cases'
      fullPath: '/citizen/my-cases'
      preLoaderRoute: typeof CitizenMyCasesRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/notifications': {
      id: '/citizen/notifications'
      path: '/notifications'
      fullPath: '/citizen/notifications'
      preLoaderRoute: typeof CitizenNotificationsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/profile': {
      id: '/citizen/profile'
      path: '/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof CitizenProfileRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/subscriptions': {
      id: '/citizen/subscriptions'
      path: '/subscriptions'
      fullPath: '/citizen/subscriptions'
      preLoaderRoute: typeof CitizenSubscriptionsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/lawyer/': {
      id: '/lawyer/'
      path: '/'
      fullPath: '/lawyer/'
      preLoaderRoute: typeof LawyerIndexRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/ai-assistant': {
      id: '/lawyer/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/lawyer/ai-assistant'
      preLoaderRoute: typeof LawyerAiAssistantRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/cases': {
      id: '/lawyer/cases'
      path: '/cases'
      fullPath: '/lawyer/cases'
      preLoaderRoute: typeof LawyerCasesRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/knowledge-base': {
      id: '/lawyer/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/lawyer/knowledge-base'
      preLoaderRoute: typeof LawyerKnowledgeBaseRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/notifications': {
      id: '/lawyer/notifications'
      path: '/notifications'
      fullPath: '/lawyer/notifications'
      preLoaderRoute: typeof LawyerNotificationsRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/profile': {
      id: '/lawyer/profile'
      path: '/profile'
      fullPath: '/lawyer/profile'
      preLoaderRoute: typeof LawyerProfileRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/qa-assistant': {
      id: '/lawyer/qa-assistant'
      path: '/qa-assistant'
      fullPath: '/lawyer/qa-assistant'
      preLoaderRoute: typeof LawyerQaAssistantRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/revenue': {
      id: '/lawyer/revenue'
      path: '/revenue'
      fullPath: '/lawyer/revenue'
      preLoaderRoute: typeof LawyerRevenueRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/lawyer/summarizer': {
      id: '/lawyer/summarizer'
      path: '/summarizer'
      fullPath: '/lawyer/summarizer'
      preLoaderRoute: typeof LawyerSummarizerRouteImport
      parentRoute: typeof LawyerRoute
    }
    '/citizen/cases/$id': {
      id: '/citizen/cases/$id'
      path: '/cases/$id'
      fullPath: '/citizen/cases/$id'
      preLoaderRoute: typeof CitizenCasesIdRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/chat/$id': {
      id: '/citizen/chat/$id'
      path: '/chat/$id'
      fullPath: '/citizen/chat/$id'
      preLoaderRoute: typeof CitizenChatIdRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/lawyer/cases/': {
      id: '/lawyer/cases/'
      path: '/'
      fullPath: '/lawyer/cases/'
      preLoaderRoute: typeof LawyerCasesIndexRouteImport
      parentRoute: typeof LawyerCasesRoute
    }
    '/lawyer/cases/$id': {
      id: '/lawyer/cases/$id'
      path: '/$id'
      fullPath: '/lawyer/cases/$id'
      preLoaderRoute: typeof LawyerCasesIdRouteImport
      parentRoute: typeof LawyerCasesRoute
    }
    '/lawyer/chat/$id': {
      id: '/lawyer/chat/$id'
      path: '/chat/$id'
      fullPath: '/lawyer/chat/$id'
      preLoaderRoute: typeof LawyerChatIdRouteImport
      parentRoute: typeof LawyerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCasesRoute: typeof AdminCasesRoute
  AdminDataManagementRoute: typeof AdminDataManagementRoute
  AdminKnowledgeBaseRoute: typeof AdminKnowledgeBaseRoute
  AdminLawyersRoute: typeof AdminLawyersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCasesRoute: AdminCasesRoute,
  AdminDataManagementRoute: AdminDataManagementRoute,
  AdminKnowledgeBaseRoute: AdminKnowledgeBaseRoute,
  AdminLawyersRoute: AdminLawyersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CitizenRouteChildren {
  CitizenCreateCaseRoute: typeof CitizenCreateCaseRoute
  CitizenMyCasesRoute: typeof CitizenMyCasesRoute
  CitizenNotificationsRoute: typeof CitizenNotificationsRoute
  CitizenProfileRoute: typeof CitizenProfileRoute
  CitizenSubscriptionsRoute: typeof CitizenSubscriptionsRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
  CitizenCasesIdRoute: typeof CitizenCasesIdRoute
  CitizenChatIdRoute: typeof CitizenChatIdRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenCreateCaseRoute: CitizenCreateCaseRoute,
  CitizenMyCasesRoute: CitizenMyCasesRoute,
  CitizenNotificationsRoute: CitizenNotificationsRoute,
  CitizenProfileRoute: CitizenProfileRoute,
  CitizenSubscriptionsRoute: CitizenSubscriptionsRoute,
  CitizenIndexRoute: CitizenIndexRoute,
  CitizenCasesIdRoute: CitizenCasesIdRoute,
  CitizenChatIdRoute: CitizenChatIdRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

interface LawyerCasesRouteChildren {
  LawyerCasesIdRoute: typeof LawyerCasesIdRoute
  LawyerCasesIndexRoute: typeof LawyerCasesIndexRoute
}

const LawyerCasesRouteChildren: LawyerCasesRouteChildren = {
  LawyerCasesIdRoute: LawyerCasesIdRoute,
  LawyerCasesIndexRoute: LawyerCasesIndexRoute,
}

const LawyerCasesRouteWithChildren = LawyerCasesRoute._addFileChildren(
  LawyerCasesRouteChildren,
)

interface LawyerRouteChildren {
  LawyerAiAssistantRoute: typeof LawyerAiAssistantRoute
  LawyerCasesRoute: typeof LawyerCasesRouteWithChildren
  LawyerKnowledgeBaseRoute: typeof LawyerKnowledgeBaseRoute
  LawyerNotificationsRoute: typeof LawyerNotificationsRoute
  LawyerProfileRoute: typeof LawyerProfileRoute
  LawyerQaAssistantRoute: typeof LawyerQaAssistantRoute
  LawyerRevenueRoute: typeof LawyerRevenueRoute
  LawyerSummarizerRoute: typeof LawyerSummarizerRoute
  LawyerIndexRoute: typeof LawyerIndexRoute
  LawyerChatIdRoute: typeof LawyerChatIdRoute
}

const LawyerRouteChildren: LawyerRouteChildren = {
  LawyerAiAssistantRoute: LawyerAiAssistantRoute,
  LawyerCasesRoute: LawyerCasesRouteWithChildren,
  LawyerKnowledgeBaseRoute: LawyerKnowledgeBaseRoute,
  LawyerNotificationsRoute: LawyerNotificationsRoute,
  LawyerProfileRoute: LawyerProfileRoute,
  LawyerQaAssistantRoute: LawyerQaAssistantRoute,
  LawyerRevenueRoute: LawyerRevenueRoute,
  LawyerSummarizerRoute: LawyerSummarizerRoute,
  LawyerIndexRoute: LawyerIndexRoute,
  LawyerChatIdRoute: LawyerChatIdRoute,
}

const LawyerRouteWithChildren =
  LawyerRoute._addFileChildren(LawyerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiDocsRoute: ApiDocsRoute,
  CitizenRoute: CitizenRouteWithChildren,
  CitizenLoginRoute: CitizenLoginRoute,
  ContactRoute: ContactRoute,
  LawyerRoute: LawyerRouteWithChildren,
  LawyerRegisterRoute: LawyerRegisterRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
